// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cukrkodfqwenyapsefio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1a3Jrb2RmcXdlbnlhcHNlZmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjU1OTYsImV4cCI6MjA1NTgwMTU5Nn0.zAYgAAWIYddMuSS7QhvTCvLHS0Qdx5GKoJwk2_mbqus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);